### ISSUE TITLE
"Bug Fix version not working"

### ISSUE THREAD

**Issue by Tomato6966** [DRSchlaubi/lyrics.kt#2]
Your version 2.3.1 (Marked as Bugs Fixed) does not work with the lavalink 4.0.4:
```
└❯ java -jar Lavalink.jar 
2024-03-16T09:08:22.776+01:00  INFO 44482 --- [           main] lavalink.server.Launcher                 : Starting Launcher v4.0.4 using Java 20 with PID 44482 (/home/Lavalinks/3500_mivatordev/Lavalink.jar started by root in /home/Lavalinks/3500_mivatordev)
2024-03-16T09:08:22.781+01:00  INFO 44482 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2024-03-16T09:08:23.638+01:00  INFO 44482 --- [           main] l.server.bootstrap.PluginManager         : Found plugin 'lavasearch-plugin' version 1.0.0
2024-03-16T09:08:23.638+01:00  INFO 44482 --- [           main] l.server.bootstrap.PluginManager         : Found plugin 'lyrics' version 1.0.1
2024-03-16T09:08:23.638+01:00  INFO 44482 --- [           main] l.server.bootstrap.PluginManager         : Found plugin 'lavadspx-plugin' version 0.0.3
2024-03-16T09:08:23.638+01:00  INFO 44482 --- [           main] l.server.bootstrap.PluginManager         : Found plugin 'plugin-template' version 0.0.2
2024-03-16T09:08:23.638+01:00  INFO 44482 --- [           main] l.server.bootstrap.PluginManager         : Found plugin 'DuncteBot-plugin' version 1.6.3
2024-03-16T09:08:23.638+01:00  INFO 44482 --- [           main] l.server.bootstrap.PluginManager         : Found plugin 'lavasrc-plugin' version 4.0.1
2024-03-16T09:08:23.642+01:00  INFO 44482 --- [           main] l.server.bootstrap.PluginManager         : Deleted ./plugins/lavalink-1.0.1.jar (new version: 2.3.1)
2024-03-16T09:08:23.642+01:00  INFO 44482 --- [           main] l.server.bootstrap.PluginManager         : Downloading https://maven.lavalink.dev/releases/dev/schlaubi/lyrics/lavalink/2.3.1/lavalink-2.3.1.jar
2024-03-16T09:08:30.074+01:00  WARN 44482 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pluginManager': Failed to instantiate [lavalink.server.bootstrap.PluginManager$$SpringCGLIB$$0]: Constructor threw exception
2024-03-16T09:08:30.087+01:00  INFO 44482 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-03-16T09:08:30.107+01:00 ERROR 44482 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pluginManager': Failed to instantiate [lavalink.server.bootstrap.PluginManager$$SpringCGLIB$$0]: Constructor threw exception
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:326) ~[spring-beans-6.0.9.jar!/:6.0.9]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:314) ~[spring-beans-6.0.9.jar!/:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-6.0.9.jar!/:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1189) ~[spring-beans-6.0.9.jar!/:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[spring-beans-6.0.9.jar!/:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.9.jar!/:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.9.jar!/:6.0.9]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.9.jar!/:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.9.jar!/:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.9.jar!/:6.0.9]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[spring-beans-6.0.9.jar!/:6.0.9]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:941) ~[spring-context-6.0.9.jar!/:6.0.9]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608) ~[spring-context-6.0.9.jar!/:6.0.9]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:733) ~[spring-boot-3.1.0.jar!/:3.1.0]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:435) ~[spring-boot-3.1.0.jar!/:3.1.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) ~[spring-boot-3.1.0.jar!/:3.1.0]
        at lavalink.server.Launcher.launchPluginBootstrap(Launcher.kt:132) ~[classes!/:4.0.4]
        at lavalink.server.Launcher.main(Launcher.kt:125) ~[classes!/:4.0.4]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[Lavalink.jar:4.0.4]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[Lavalink.jar:4.0.4]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[Lavalink.jar:4.0.4]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[Lavalink.jar:4.0.4]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [lavalink.server.bootstrap.PluginManager$$SpringCGLIB$$0]: Constructor threw exception
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224) ~[spring-beans-6.0.9.jar!/:6.0.9]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:110) ~[spring-beans-6.0.9.jar!/:6.0.9]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:323) ~[spring-beans-6.0.9.jar!/:6.0.9]
        ... 23 common frames omitted
Caused by: java.io.IOException: Server returned HTTP response code: 502 for URL: https://maven.lavalink.dev/releases/dev/schlaubi/lyrics/lavalink/2.3.1/lavalink-2.3.1.jar
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1980) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1581) ~[na:na]
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[na:na]
        at java.base/java.net.URL.openStream(URL.java:1317) ~[na:na]
        at lavalink.server.bootstrap.PluginManager.downloadJar(PluginManager.kt:92) ~[classes!/:4.0.4]
        at lavalink.server.bootstrap.PluginManager.manageDownloads(PluginManager.kt:84) ~[classes!/:4.0.4]
        at lavalink.server.bootstrap.PluginManager.<init>(PluginManager.kt:27) ~[classes!/:4.0.4]
        at lavalink.server.bootstrap.PluginManager$$SpringCGLIB$$0.<init>(<generated>) ~[classes!/:4.0.4]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484) ~[na:na]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211) ~[spring-beans-6.0.9.jar!/:6.0.9]
        ... 25 common frames omitted

```

```
$ java --version
openjdk 20 2023-03-21
OpenJDK Runtime Environment (build 20+36-2344)
OpenJDK 64-Bit Server VM (build 20+36-2344, mixed mode, sharing)
```

```
$ hostnamectl
   Static hostname: ...
         Icon name: computer-vm
           Chassis: vm
        Machine ID: ...
           Boot ID: ...
    Virtualization: kvm
  Operating System: Ubuntu 20.04.6 LTS
            Kernel: Linux 5.4.0-173-generic
      Architecture: x86-64
```

**Comment by DRSchlaubi** [comment]
@topi314 fix your Internet
